const PASSPORT_SEPARATOR = '*'
const PASSPORT_KEY_SEPARATOR = ' '
const PASSPORT_KEY_VALUE_SEPARATOR = ':'

export default {
  PASSPORT_SEPARATOR,
  PASSPORT_KEY_SEPARATOR,
  PASSPORT_KEY_VALUE_SEPARATOR,
}
