const PASSPORT_OLD_SEPARATOR = `

`
const PASSPORT_NEW_SEPARATOR = '*'
const PASSPORT_KEY_SEPARATOR = ' '
const PASSPORT_KEY_VALUE_SEPARATOR = ':'

export default {
  PASSPORT_OLD_SEPARATOR,
  PASSPORT_NEW_SEPARATOR,
  PASSPORT_KEY_SEPARATOR,
  PASSPORT_KEY_VALUE_SEPARATOR,
}
